apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy
  project: default
  source:
    repoURL: https://github.com/kamuridesu/argocd-k3s-base-config.git
    path: charts/haproxy
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
        - CreateNamespace=true
